version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: prediction_log
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mounting the init.sql script
    networks:
      - app_network

  streamlit:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    networks:
      - app_network
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: prediction_log
      DATABASE_USER: postgres
      DATABASE_PASSWORD: mysecretpassword

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
